# @package _global_
# Evaluation configuration options

# Evaluation parameters
n_eval_batches: 10
eval_batch_size_prompts: null  # useful if evals cause OOM
eval_every_n_wandb_logs: 100  # logs every 1000 steps 
