defaults:
  - _self_
  - experiment: basic
  - launcher: base
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    env_set:
      TOKENIZERS_PARALLELISM: "false"
      SAE_LENS_LOG_LEVEL: "DEBUG"
