# @package _global_
# JumpReLU SAE Architecture Configuration

architecture: "jumprelu"
activation_fn: "relu"  # Will be set to appropriate default in post_init
activation_fn_kwargs: {}
expansion_factor: 4

# JumpReLU specific parameters
jumprelu_init_threshold: 0.001
jumprelu_bandwidth: 0.001 
