# @package _global_
# Cosine Annealing Learning Rate Schedule

defaults:
  - default

# Learning rate schedule
lr_scheduler_name: "cosineannealing"
lr_warm_up_steps: 1000
lr_end: 3e-5  # lr / 10
lr_decay_steps: 10000 
